# Generated by Django 6.0 on 2025-12-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('targets_processed', models.IntegerField(default=0)),
                ('urls_checked', models.IntegerField(default=0)),
                ('event_sources_found', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the target (e.g., 'Newton', 'MIT', 'Museum of Fine Arts')", max_length=255)),
                ('target_type', models.CharField(choices=[('town', 'Town'), ('university', 'University'), ('museum', 'Museum'), ('library', 'Library'), ('organization', 'Organization'), ('venue', 'Venue')], default='town', max_length=20)),
                ('location', models.CharField(blank=True, help_text="Location for disambiguation (e.g., 'MA', 'Boston, MA')", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_file', models.CharField(blank=True, help_text='CSV/file this target was imported from', max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'target_type', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, help_text='Search category (library, parks, town, museum, community)', max_length=50)),
                ('screenshot_path', models.CharField(blank=True, max_length=500)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('location_correct', models.BooleanField(help_text='Is this the correct location?', null=True)),
                ('location_found', models.CharField(blank=True, help_text='Location detected on page', max_length=255)),
                ('has_events', models.BooleanField(help_text='Does this page have events?', null=True)),
                ('event_count', models.IntegerField(help_text='Approximate number of events visible', null=True)),
                ('org_type', models.CharField(blank=True, help_text='Organization type detected', max_length=50)),
                ('confidence', models.CharField(blank=True, help_text='Classification confidence (high/medium/low)', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Explanation from vision model')),
                ('model_used', models.CharField(blank=True, help_text='Vision model used for classification', max_length=50)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('pushed_to_api', models.BooleanField(default=False)),
                ('pushed_at', models.DateTimeField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='navigator.target')),
            ],
            options={
                'verbose_name_plural': 'Discoveries',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Search query to use', max_length=500)),
                ('category', models.CharField(blank=True, help_text="Category this query is for (e.g., 'library', 'events')", max_length=50)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_queries', to='navigator.target')),
            ],
            options={
                'verbose_name_plural': 'Target queries',
            },
        ),
    ]
