# Generated by Django 6.0 on 2025-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='org_type',
            field=models.CharField(blank=True, help_text='Organization type detected', max_length=255),
        ),
    ]
