# Generated by Django 6.0 on 2026-01-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0002_alter_discovery_org_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_type', models.CharField(max_length=10)),
                ('osm_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('library', 'Library'), ('museum', 'Museum'), ('community_centre', 'Community Center'), ('theatre', 'Theatre'), ('arts_centre', 'Arts Center'), ('school', 'School'), ('university', 'University'), ('park', 'Park'), ('playground', 'Playground'), ('sports_centre', 'Sports Center'), ('townhall', 'Town Hall')], max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='MA', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('osm_website', models.URLField(blank=True, max_length=500)),
                ('osm_phone', models.CharField(blank=True, max_length=50)),
                ('osm_opening_hours', models.TextField(blank=True)),
                ('osm_operator', models.CharField(blank=True, max_length=255)),
                ('osm_wikidata', models.CharField(blank=True, max_length=50)),
                ('venue_status', models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced to Backend'), ('failed', 'Sync Failed')], default='pending', max_length=20)),
                ('venue_id', models.IntegerField(blank=True, help_text='ID in main superschedules system', null=True)),
                ('venue_synced_at', models.DateTimeField(blank=True, null=True)),
                ('venue_sync_error', models.TextField(blank=True)),
                ('source_status', models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('discovered', 'Events Page Found'), ('no_events', 'No Events Page Found'), ('skipped', 'Skipped (no website)')], default='not_started', max_length=20)),
                ('discovered_events_url', models.URLField(blank=True, max_length=500)),
                ('discovery_method', models.CharField(blank=True, max_length=50)),
                ('discovery_confidence', models.FloatField(blank=True, null=True)),
                ('discovery_notes', models.TextField(blank=True)),
                ('source_id', models.IntegerField(blank=True, help_text='Source ID in main superschedules system', null=True)),
                ('source_synced_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'POI',
                'verbose_name_plural': 'POIs',
                'indexes': [models.Index(fields=['venue_status'], name='navigator_p_venue_s_914309_idx'), models.Index(fields=['source_status'], name='navigator_p_source__635b67_idx'), models.Index(fields=['category'], name='navigator_p_categor_207fcf_idx'), models.Index(fields=['city', 'state'], name='navigator_p_city_3b9f16_idx')],
                'unique_together': {('osm_type', 'osm_id')},
            },
        ),
    ]
