# Generated by Django 6.0 on 2026-01-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0003_add_poi_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('extract', 'POI Extraction'), ('sync', 'Venue Sync'), ('discover', 'Source Discovery')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('city_filter', models.CharField(blank=True, max_length=100)),
                ('limit', models.IntegerField(default=0)),
                ('dry_run', models.BooleanField(default=False)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('current_item', models.CharField(blank=True, max_length=255)),
                ('created', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('unchanged', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pipeline Run',
                'verbose_name_plural': 'Pipeline Runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
