# Generated by Django 6.0 on 2026-01-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0004_add_pipeline_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text="Domain to block (e.g., 'eventbrite.com')", max_length=255, unique=True)),
                ('reason', models.CharField(blank=True, help_text='Why this domain is blocked', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.AddField(
            model_name='discovery',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='discovery',
            name='state',
            field=models.CharField(default='MA', max_length=2),
        ),
        migrations.AddField(
            model_name='poi',
            name='discovery',
            field=models.ForeignKey(blank=True, help_text='Event source for this POI (shared with similar POIs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pois', to='navigator.discovery'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='navigator.target'),
        ),
        migrations.CreateModel(
            name='WorkerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_type', models.CharField(choices=[('url_discovery', 'URL Discovery Worker')], max_length=50, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('current_poi_name', models.CharField(blank=True, max_length=255)),
                ('pois_processed', models.IntegerField(default=0)),
                ('discoveries_found', models.IntegerField(default=0)),
                ('discoveries_reused', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('batch_size', models.IntegerField(default=1)),
                ('sleep_seconds', models.FloatField(default=2.0)),
                ('current_poi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigator.poi')),
            ],
            options={
                'verbose_name': 'Worker Status',
                'verbose_name_plural': 'Worker Statuses',
            },
        ),
    ]
