# Generated by Django 6.0 on 2026-01-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0005_add_worker_and_poi_discovery_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='discovered_website',
            field=models.URLField(blank=True, help_text='Website found via web search', max_length=500),
        ),
        migrations.AddField(
            model_name='poi',
            name='website_discovery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='website_status',
            field=models.CharField(choices=[('has_osm', 'Has OSM Website'), ('not_started', 'Not Started'), ('processing', 'Processing'), ('found', 'Website Found'), ('not_found', 'No Website Found'), ('failed', 'Search Failed')], default='not_started', max_length=20),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['website_status'], name='navigator_p_website_d01928_idx'),
        ),
    ]
