# Generated by Django 6.0 on 2026-01-13 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0006_add_website_discovery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='events_url',
            field=models.URLField(blank=True, help_text='URL where events are listed for this venue', max_length=500),
        ),
        migrations.AddField(
            model_name='poi',
            name='events_url_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='events_url_method',
            field=models.CharField(blank=True, help_text='How events URL was found', max_length=50),
        ),
        migrations.AddField(
            model_name='poi',
            name='events_url_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poi',
            name='discovery',
            field=models.ForeignKey(blank=True, help_text='Discovery record (for tracking/history)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pois', to='navigator.discovery'),
        ),
    ]
