# Generated by Django 6.0 on 2026-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0007_add_events_url_to_poi'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstatus',
            name='current_phase',
            field=models.CharField(blank=True, help_text="'website' or 'events'", max_length=20),
        ),
        migrations.AddField(
            model_name='workerstatus',
            name='websites_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerstatus',
            name='websites_not_found',
            field=models.IntegerField(default=0),
        ),
    ]
