# Generated by Django 6.0 on 2026-01-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0008_add_worker_website_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='source_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('discovered', 'Events Page Found'), ('validated', 'LLM Validated'), ('rejected', 'LLM Rejected'), ('no_events', 'No Events Page Found'), ('skipped', 'Skipped (no website)')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='poi',
            name='website_status',
            field=models.CharField(choices=[('has_osm', 'Has OSM Website'), ('not_started', 'Not Started'), ('processing', 'Processing'), ('found', 'Website Found'), ('validated', 'LLM Validated'), ('rejected', 'LLM Rejected'), ('not_found', 'No Website Found'), ('failed', 'Search Failed')], default='not_started', max_length=20),
        ),
    ]
